<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Artisan;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        // Generate Filament/Shield permissions for the app panel.
        Artisan::call('shield:generate', [
            '--all' => true,
            '--option' => 'permissions',
            '--panel' => 'app',
            '--no-interaction' => true,
        ]);

        // Custom permissions are not generated by Shield.
        foreach (array_keys(config('filament-shield.custom_permissions', [])) as $customPermission) {
            Permission::findOrCreate($customPermission, 'web');
        }

        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $superAdmin = Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);
        $admin = Role::firstOrCreate(['name' => 'admin', 'guard_name' => 'web']);
        $user = Role::firstOrCreate(['name' => 'user', 'guard_name' => 'web']);

        $allPermissionIds = Permission::query()
            ->where('guard_name', 'web')
            ->pluck('id')
            ->unique()
            ->values()
            ->all();

        // Super admin keeps full access (also covered by Shield gate intercept).
        $superAdmin->permissions()->sync($allPermissionIds);

        // Admin preset: full operational access, no role-management permissions and
        // read-only access to the global catalog, which only super admins may change.
        $adminPermissionIds = Permission::query()
            ->where('guard_name', 'web')
            ->where('name', 'not like', '%:Role')
            ->get()
            ->reject(fn (Permission $permission): bool => self::changesGlobalCatalog($permission->name))
            ->pluck('id')
            ->unique()
            ->values()
            ->all();
        $admin->permissions()->sync($adminPermissionIds);

        // User preset: focused operational permissions.
        $userPermissionNames = [
            'ViewAny:Task',
            'View:Task',
            'Create:Task',
            'Update:Task',
            'ViewAny:Inventory',
            'View:Inventory',
            'ViewAny:Stock',
            'View:Stock',
            'ViewAny:Product',
            'View:Product',
            'ViewAny:Movement',
            'View:Movement',
            'Create:Movement',
            'Update:Movement',
            'ViewAny:Reorder',
            'View:Reorder',
            'ViewAny:ReorderOrder',
            'View:ReorderOrder',
            'Create:ReorderOrder',
            'Update:ReorderOrder',
            'Transition:ReorderOrder',
            'ViewAny:TaskStatus',
            'View:TaskStatus',
            'ViewAny:TaskType',
            'View:TaskType',
            'ViewAny:InventoryLocation',
            'View:InventoryLocation',
            'ViewAny:InventoryPosition',
            'View:InventoryPosition',
            'ViewAny:Scope',
            'View:Scope',
            'View:CurrentScopeWidget',
            'View:StatsOverview',
            'View:MovementChart',
            'View:TaskChart',
        ];

        $userPermissionIds = Permission::query()
            ->where('guard_name', 'web')
            ->whereIn('name', $userPermissionNames)
            ->pluck('id')
            ->unique()
            ->values()
            ->all();
        $user->permissions()->sync($userPermissionIds);

        app()[PermissionRegistrar::class]->forgetCachedPermissions();
    }

    /**
     * Whether the permission (Affix:Subject, e.g. Update:Product) allows
     * changing a global catalog entity.
     */
    public static function changesGlobalCatalog(string $permission): bool
    {
        [$affix, $subject] = array_pad(explode(':', $permission, 2), 2, '');

        return ! in_array($affix, ['View', 'ViewAny'], true)
            && in_array($subject, ['Product', 'ProductBrand', 'ProductGroup', 'ProductModel', 'ProductType', 'TaskStatus', 'TaskType'], true);
    }
}
