<?php

use Illuminate\Database\Migrations\Migration;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

return new class extends Migration
{
    /**
     * The dashboard widgets now check their Shield permission: grant it to the
     * preset roles, which could already see every widget.
     */
    public function up(): void
    {
        $permissions = collect([
            'view_current_scope_widget',
            'view_stats_overview',
            'view_movement_chart',
            'view_task_chart',
        ])->map(fn (string $name): Permission => Permission::findOrCreate($name, 'web'));

        Role::query()
            ->where('guard_name', 'web')
            ->whereIn('name', ['super_admin', 'admin', 'user'])
            ->get()
            ->each(fn (Role $role) => $role->givePermissionTo($permissions));

        app(PermissionRegistrar::class)->forgetCachedPermissions();
    }

    /**
     * The permissions are generated by Shield: they are kept on rollback.
     */
    public function down(): void
    {
        //
    }
};
